---
title: "Do_seq_pre_pro"
output: html_document
---

# Loading
First load required libraries and set wd for this project and load in sequencing data. 
```{r, echo=FALSE}
library(tidyverse)

setwd("C:/Users/brouw192/Wageningen University & Research/Dojran project - Documents/data/sedaDNA/pre_processed")

Doj_pre_pro_df_raw <- read_tsv("C:/Users/brouw192/Wageningen University & Research/Dojran project - Documents/data/sedaDNA/external/seq_data/dojran_shotgun_data.tsv")

```
# Simplifying df's
To make it easier to work we simplify the df we get from Kevin.
I'll make multiple, df_genus, df_genus_family etc. but for now only focus on genus data, so we only extract data from the df_raw which is relevant for the df_gs (genus dataframe). 
```{r, echo = FALSE}
# Define relevant columns for a genus df
columns_df_gs <- c(
  "library",
  "core",
  "depth_cm",
  "depth",
  "phylum_name",
  "order_name",
  "family_name",
  "genus_name",
  "taxa_name", # taxa in this case refers to the reference genome which the read is mapped to, res is genus still
  "genus_count_assembly",
  "genus_deam_count",
  "sum_genus_count",
  "median_read_length_genus",
  "ancientness_genus",
  "deam5p_frac_genus",
  "deam3p_frac_genus"
  )

columns_df_gs_fm <- c(
  "library",
  "core",
  "depth_cm",
  "depth",
  "phylum_name",
  "order_name",
  "family_name",
  "genus_name",
  "taxa_name", # taxa in this case refers to the reference genome which the read is mapped to, res is genus still
  "genus_count_assembly",
  "genus_deam_count",
  "sum_genus_count",
  "median_read_length_genus",
  "ancientness_genus",
  "deam5p_frac_genus",
  "deam3p_frac_genus",
  "family_count_assembly",
  "family_deam_count",
  "sum_family_count",
  "median_read_length_family",
  "ancientness_family",
  "deam5p_frac_family",
  "deam3p_frac_family"
  )
```

```{r, echo=FALSE}
Doj_pre_pro_df_gs <- Doj_pre_pro_df_raw %>% # so we define the genus data frame (df_gs) from the raw df. 
  #filter(!library %in% c("")) # This line is for removing f.e. libraries of blanks
  select(all_of(columns_df_gs)) %>% # use select to only select columns relevant for df_gs 
  group_by(library, genus_name) %>%
  slice_max(genus_count_assembly, n =1, with_ties = FALSE) %>% # this step is to only keep the assembly with the max genus counts. This                                                                  so we don't have double genus entries per library. number of unique                                                                    reads per genus are in sum_genus_count
  mutate(deam_rate_genus = (deam5p_frac_genus + deam3p_frac_genus) / 2)  %>% #add deamination rate
  filter(!genus_count_assembly < 10) %>% # filter out entries with lower than 10 reads, this low reads = generaly unreliable 
  ungroup() %>%
  group_by(core, depth)

```

 
 
